[build]
  command = "bun run build"
  publish = "dist"

# Pin Bun so Netlify uses the Bun runtime during builds
[build.environment]
  BUN_VERSION = "1.1.31"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
